import type { ZipRow, Scope, Metrics, History, Observation } from './types';
export function median(values:(number|null)[]):number|null { const clean=values.filter((v):v is number=>v!==null&&Number.isFinite(v)).sort((a,b)=>a-b);const n=clean.length;return n?(n%2?clean[(n-1)/2]:(clean[n/2-1]+clean[n/2])/2):null; }
export function matches(r:ZipRow,s:Scope){return (!s.state||r.state===s.state)&&(!s.metro||r.metro===s.metro)&&(!s.city||r.city===s.city);}
export function metrics(rows:ZipRow[]):Metrics{return {count:rows.length,home:median(rows.map(r=>r.home)),rent:median(rows.map(r=>r.rent)),gross:median(rows.map(r=>r.rent*1200/r.home)),homeYoy:median(rows.map(r=>r.homeYoy)),rentYoy:median(rows.map(r=>r.rentYoy)),coverage:rows.length?100*rows.filter(r=>r.homeYoy!==null).length/rows.length:null};}
export function groups(rows:ZipRow[],by:'state'|'metro'){const buckets=new Map<string,ZipRow[]>();for(const r of rows){const k=r[by]||'Unassigned metro'; if(!buckets.has(k))buckets.set(k,[]);buckets.get(k)!.push(r);}return [...buckets].map(([name,rs])=>({name,...metrics(rs)}));}
export function aggregateHistory(history:History, zips:string[]):[number,number,number,number][]{const buckets=new Map<number,Observation[]>();for(const z of zips)for(const v of history[z]??[]){if(!buckets.has(v[0]))buckets.set(v[0],[]);buckets.get(v[0])!.push(v);}return [...buckets].sort((a,b)=>a[0]-b[0]).map(([m,vs])=>[m,median(vs.map(v=>v[1]))!,median(vs.map(v=>v[2]))!,vs.length]);}
export const money=(n:number|null,compact=false)=>n===null?'—':new Intl.NumberFormat('en-US',{style:'currency',currency:'USD',maximumFractionDigits:compact?1:0,...compact?{notation:'compact' as const}:{}}).format(n);
export const pct=(n:number|null,sign=false)=>n===null?'—':`${sign&&n>0?'+':''}${n.toFixed(2)}%`;
export const num=(n:number)=>new Intl.NumberFormat('en-US').format(n);
export const dateLabel=(s:string)=>new Intl.DateTimeFormat('en-GB',{month:'short',year:'numeric',timeZone:'UTC'}).format(new Date(s+'T12:00:00Z'));
export const csvCell=(v:unknown)=>{const s=v===null||v===undefined?'':String(v);return /^[=+@\-]/.test(s)&&typeof v==='string'?`"'${s.replaceAll('"','""')}"`:`"${s.replaceAll('"','""')}"`;};
export function downloadCsv(name:string, headers:string[],rows:unknown[][]){const text=[headers,...rows].map(r=>r.map(csvCell).join(',')).join('\r\n');const url=URL.createObjectURL(new Blob(['\ufeff'+text],{type:'text/csv;charset=utf-8'}));const a=document.createElement('a');a.href=url;a.download=name;document.body.appendChild(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(url),1000);}
