'use client';
import { useEffect, useRef, useState } from 'react';
import type { PlotPoint,Metrics } from './types';
import { money,pct,num } from './analytics';
function useWidth(){const ref=useRef<HTMLDivElement>(null);const [width,setWidth]=useState(560);useEffect(()=>{const el=ref.current;if(!el)return;const o=new ResizeObserver(([r])=>setWidth(Math.max(220,r.contentRect.width)));o.observe(el);return ()=>o.disconnect();},[]);return {ref,width};}
export function LineChart({points,title,subtitle,unit='money',forecast=[],interval=80,onExport}:{points:PlotPoint[];title:string;subtitle?:string;unit?:'money'|'pct';forecast?:PlotPoint[];interval?:number;onExport?:()=>void}){
 const {ref,width:w}=useWidth(),[hover,setHover]=useState<PlotPoint|null>(null);const all=[...points,...forecast];const h=272,l=66,r=22,t=24,b=37;const ys=all.flatMap(p=>[p.y,...p.lower===undefined?[]:[p.lower],...p.upper===undefined?[]:[p.upper]]);const minimum=ys.length?Math.min(...ys):0,maximum=ys.length?Math.max(...ys):1,pad=(maximum-minimum)*.13||maximum*.04||1;const lo=Math.max(0,minimum-pad),hi=maximum+pad;const xs=all.map(p=>p.x),xlo=xs.length?Math.min(...xs):0,xhi=xs.length?Math.max(...xs):1;const x=(v:number)=>l+(v-xlo)/(xhi-xlo||1)*(w-l-r),y=(v:number)=>h-b-(v-lo)/(hi-lo||1)*(h-t-b);const path=(ps:PlotPoint[],gaps=false)=>ps.map((p,i)=>`${i&&(!gaps||p.x-ps[i-1].x<=1)?'L':'M'}${x(p.x).toFixed(2)},${y(p.y).toFixed(2)}`).join(' ');const format=(v:number)=>unit==='pct'?pct(v):money(v,true);const ticks=[0,1,2,3].map(i=>lo+(hi-lo)*i/3);const labelled=all.length?[all[0],all[Math.floor((all.length-1)/2)],all[all.length-1]]:[];
 const nearest=(event:React.PointerEvent<SVGSVGElement>)=>{const bounds=event.currentTarget.getBoundingClientRect(),cx=event.clientX-bounds.left;const p=all.reduce<PlotPoint|null>((a,p)=>!a||Math.abs(x(p.x)-cx)<Math.abs(x(a.x)-cx)?p:a,null);setHover(p);};
 return <section className="ef-panel ef-chart" ref={ref}><div className="ef-panel-head"><div><h3>{title}</h3>{subtitle?<p>{subtitle}</p>:null}</div>{onExport?<button type="button" className="ef-text-button" onClick={onExport}>Export CSV</button>:null}</div>{all.length?<><svg viewBox={`0 0 ${w} ${h}`} role="img" aria-label={`${title}. ${points.length} observed months${forecast.length?`, ${forecast.length-1} forecast horizons with ${interval}% intervals`:''}.`} onPointerMove={nearest} onPointerLeave={()=>setHover(null)}>
 <defs><linearGradient id={`fill-${title.replaceAll(' ','-')}`} x1="0" y1="0" x2="0" y2="1"><stop offset="0%" stopColor="var(--ef-gold)" stopOpacity=".14"/><stop offset="100%" stopColor="var(--ef-gold)" stopOpacity="0"/></linearGradient></defs>
 {ticks.map(v=><g key={v}><line x1={l} x2={w-r} y1={y(v)} y2={y(v)} className="ef-grid-line"/><text x={l-12} y={y(v)+4} textAnchor="end" className="ef-axis-label">{format(v)}</text></g>)}
 {labelled.map((p,i)=><text key={i} x={x(p.x)} y={h-10} textAnchor={i===0?'start':i===2?'end':'middle'} className="ef-axis-label">{p.label}</text>)}
 {points.length>1&&points.every((p,i)=>!i||p.x-points[i-1].x<=1)?<path d={`${path(points)} L${x(points[points.length-1].x)},${h-b} L${x(points[0].x)},${h-b} Z`} fill={`url(#fill-${title.replaceAll(' ','-')})`}/>:null}
 {forecast.length>1?<path d={forecast.map((p,i)=>`${i?'L':'M'}${x(p.x)},${y(p.upper??p.y)}`).join(' ')+[...forecast].reverse().map(p=>`L${x(p.x)},${y(p.lower??p.y)}`).join(' ')+' Z'} className="ef-interval-band"/>:null}
 <path d={path(points,true)} className="ef-observed-line"/>{forecast.length?<path d={path(forecast)} className="ef-forecast-line"/>:null}
 {forecast.map(p=><circle key={p.x} cx={x(p.x)} cy={y(p.y)} r="3" className="ef-forecast-dot"/>)}
 {hover?<g><line x1={x(hover.x)} x2={x(hover.x)} y1={t} y2={h-b} className="ef-hover-line"/><circle cx={x(hover.x)} cy={y(hover.y)} r="4" className="ef-hover-dot"/></g>:null}
 </svg><div className="ef-chart-readout">{hover?<><strong>{hover.label}</strong><span>{money(hover.y)}{hover.lower!==undefined?` · ${interval}% range ${money(hover.lower)}–${money(hover.upper!)}`:''}{hover.count?` · ${num(hover.count)} ZIPs`:''}</span></>:forecast.length?<><span className="ef-key">Observed</span><span className="ef-key projected">Projection</span><span>{interval}% empirical interval</span></>:<span>Monthly median across matched ZIPs. Coverage varies by month.</span>}</div></>:<div className="ef-empty">No observed history for this selection.</div>}</section>;
}
export function Scatter({rows,onSelect}:{rows:({name:string}&Metrics)[];onSelect:(name:string)=>void}){
 const {ref,width:w}=useWidth();const h=295,l=62,r=24,t=24,b=51;const valid=rows.filter((p):p is {name:string}&Metrics&{homeYoy:number;gross:number}=>p.homeYoy!==null&&p.gross!==null);const lo=Math.min(0,...valid.map(p=>p.homeYoy))-.6,hi=Math.max(0,...valid.map(p=>p.homeYoy))+.6,yhi=Math.max(1,...valid.map(p=>p.gross))*1.16;const x=(v:number)=>l+(v-lo)/(hi-lo||1)*(w-l-r),y=(v:number)=>h-b-v/yhi*(h-t-b);const [active,setActive]=useState<typeof valid[number]|null>(null);
 return <section className="ef-panel" ref={ref}><div className="ef-panel-head"><div><h3>Growth & rent-to-value</h3><p>Bubble size shows matched ZIP count. Select a market to filter.</p></div></div>{valid.length?<><svg viewBox={`0 0 ${w} ${h}`} role="img" aria-label="Home value year-over-year growth against gross rent-to-value by market"><text x={l} y={14} className="ef-axis-label">Gross rent-to-value %</text>{[0,1,2,3].map(i=>{const v=yhi*i/3;return <g key={i}><line x1={l} x2={w-r} y1={y(v)} y2={y(v)} className="ef-grid-line"/><text x={l-10} y={y(v)+4} textAnchor="end" className="ef-axis-label">{v.toFixed(1)}%</text></g>})}<line x1={x(0)} x2={x(0)} y1={t} y2={h-b} className="ef-hover-line"/>{[lo,(lo+hi)/2,hi].map(v=><text key={v} x={x(v)} y={h-b+20} textAnchor="middle" className="ef-axis-label">{v.toFixed(1)}%</text>)}<text x={w/2} y={h-5} textAnchor="middle" className="ef-axis-label">Home value growth · year over year</text>{valid.map(p=><g key={p.name} role="button" tabIndex={0} aria-label={`${p.name}: home growth ${pct(p.homeYoy)}, gross rent-to-value ${pct(p.gross)}, ${p.count} ZIPs. Filter market.`} onPointerEnter={()=>setActive(p)} onFocus={()=>setActive(p)} onClick={()=>onSelect(p.name)} onKeyDown={e=>{if(e.key==='Enter'||e.key===' '){e.preventDefault();onSelect(p.name);}}}><circle cx={x(p.homeYoy)} cy={y(p.gross)} r={Math.min(18,5+Math.sqrt(p.count)*.36)} className="ef-market-dot"/><circle cx={x(p.homeYoy)} cy={y(p.gross)} r="17" fill="transparent"/></g>)}</svg><div className="ef-chart-readout">{active?<><strong>{active.name}</strong><span>{pct(active.homeYoy,true)} home growth · {pct(active.gross)} gross · {num(active.count)} ZIPs</span></>:<span>Markets without a valid growth comparison are omitted.</span>}</div></>:<div className="ef-empty">No markets with a valid year-over-year comparison.</div>}</section>;
}
export function Momentum({rows,onSelect}:{rows:({name:string}&Metrics)[];onSelect:(name:string)=>void}){const ranked=rows.filter(r=>r.rentYoy!==null).sort((a,b)=>b.rentYoy!-a.rentYoy!).slice(0,8);const max=Math.max(1,...ranked.map(r=>Math.abs(r.rentYoy!)));return <section className="ef-panel"><div className="ef-panel-head"><div><h3>Rent momentum</h3><p>Top eight markets by median year-over-year rent growth.</p></div></div><div className="ef-momentum">{ranked.length?ranked.map(r=><button className="ef-momentum-row" key={r.name} onClick={()=>onSelect(r.name)}><span>{r.name}</span><i><b style={{left:r.rentYoy!<0?`${50-50*Math.abs(r.rentYoy!)/max}%`:'50%',width:`${50*Math.abs(r.rentYoy!)/max}%`}} className={r.rentYoy!<0?'negative':''}/></i><strong>{pct(r.rentYoy,true)}</strong></button>):<p className="ef-empty">No valid year-over-year rent comparisons.</p>}</div></section>}
